#
# Copyright (c) 2018 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#


CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="Nordic_OTA"



CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

# CONFIG_BOOTLOADER_MCUBOOT=y    #if not usign sysbuild.

CONFIG_NCS_SAMPLE_MCUMGR_BT_OTA_DFU=y

CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y

CONFIG_SETTINGS=y

#RTT
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n
CONFIG_USE_SEGGER_RTT=y

CONFIG_LOG=y

CONFIG_SENSOR=y
CONFIG_I2C=y

#TMP117 sensor
CONFIG_TMP116=y
#BMI270 sensor
CONFIG_BMI270=y
#MAX30101
CONFIG_MAX30101=y